import type { LearningModuleContent } from '@/services/ai/ai.types';

export function downloadStudyGuide(moduleContent: LearningModuleContent, studentName: string) {
  const fileContent = `================================================================================
AETHER LEARN — OFFICIAL COMPREHENSIVE STUDY GUIDE
Topic: ${moduleContent.title}
Student: ${studentName}
Date: ${new Date().toLocaleDateString('en-US', { dateStyle: 'full' })}
================================================================================

1. CORE CONCEPT OVERVIEW
--------------------------------------------------------------------------------
Concept: ${moduleContent.conceptName}
Mastery Target Level: ${moduleContent.explanationLevel}

${moduleContent.explanation}

2. KEY TAKEAWAY IDEA
--------------------------------------------------------------------------------
"${moduleContent.keyIdea}"

3. WORKED REAL-WORLD EXAMPLE
--------------------------------------------------------------------------------
Scenario:
${moduleContent.example.scenario}

${moduleContent.example.codeOrDiagram ? `Code / Diagram Breakdown:\n${moduleContent.example.codeOrDiagram}\n` : ''}
Explanation:
${moduleContent.example.explanation}

4. SELF-ASSESSMENT CHECK
--------------------------------------------------------------------------------
Question: ${moduleContent.tryItQuestion.question}
Answer: ${moduleContent.tryItQuestion.answer}
Explanation: ${moduleContent.tryItQuestion.explanation}

================================================================================
Generated by MetaMind Adaptive AI Platform • Keep learning, stay curious!
================================================================================`;

  const blob = new Blob([fileContent], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `MetaMind_Study_Guide_${moduleContent.conceptName.replace(/\s+/g, '_')}.txt`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
